import enum


class G2PRegistryErrorCodes(enum.Enum):
    # Request Validation Errors
    INVALID_REQUEST = ("INVALID_REQUEST", "REQ-VAL-000")
    REQUEST_VALIDATION_ERROR = ("REQUEST_VALIDATION_ERROR", "REQ-VAL-001")

    # Database Errors
    DATABASE_CONNECTION_ERROR = ("DATABASE_CONNECTION_ERROR", "DB-ERR-001")
    DATABASE_QUERY_ERROR = ("DATABASE_QUERY_ERROR", "DB-ERR-002")
    DATABASE_TRANSACTION_ERROR = ("DATABASE_TRANSACTION_ERROR", "DB-ERR-003")

    # Register Errors
    REGISTER_NOT_FOUND = ("REGISTER_NOT_FOUND", "REG-ERR-001")
    REGISTER_DATA_NOT_FOUND = ("REGISTER_DATA_NOT_FOUND", "REG-ERR-002")
    CHANGE_REQUEST_NOT_FOUND = ("CHANGE_REQUEST_NOT_FOUND", "REG-ERR-003")
    CHANGE_REQUEST_NOT_IN_PENDING_STATE = ("CHANGE_REQUEST_NOT_IN_PENDING_STATE", "REG-ERR-004")
    VERIFICATIONS_PENDING = ("VERIFICATIONS_PENDING", "REG-ERR-005")
    SECTION_NOT_FOUND = ("SECTION_NOT_FOUND", "REG-ERR-006")
    UNKNOWN_CHANGE_REQUEST_ACTION = ("UNKNOWN_CHANGE_REQUEST_ACTION", "REG-ERR-007")
    INTAKE_FORM_NOT_FOUND = ("INTAKE_FORM_NOT_FOUND", "REG-ERR-008")
    INTAKE_FORM_INVALID_STATE = ("INTAKE_FORM_INVALID_STATE", "REG-ERR-009")
    INTAKE_FORM_VERIFICATIONS_PENDING = ("INTAKE_FORM_VERIFICATIONS_PENDING", "REG-ERR-010")

    # Partner Errors
    PARTNER_NOT_REGISTERED = ("PARTNER_NOT_REGISTERED", "REGP-ERR-001")
    DATA_MODEL_NOT_FOUND = ("DATA_MODEL_NOT_FOUND", "REGP-ERR-002")

    # Ingestion Errors
    PARTNER_ALREADY_EXISTS = ("PARTNER_ALREADY_EXISTS", "ING-ERR-001")
    PARTNER_NOT_FOUND = ("PARTNER_NOT_FOUND", "ING-ERR-002")
    PATTERN_NOT_FOUND = ("PATTERN_NOT_FOUND", "ING-ERR-003")
    SEMANTIC_PATTERN_NOT_FOUND = ("SEMANTIC_PATTERN_NOT_FOUND", "ING-ERR-004")
    PAYLOAD_ENRICHER_NOT_FOUND = ("PAYLOAD_ENRICHER_NOT_FOUND", "ING-ERR-006")
    DATA_MODEL_ALREADY_EXISTS = ("DATA_MODEL_ALREADY_EXISTS", "ING-ERR-007")

    # Outgestion Errors
    TOPIC_NOT_FOUND = ("TOPIC_NOT_FOUND", "OUT-ERR-001")
    TOPIC_ALREADY_EXISTS = ("TOPIC_ALREADY_EXISTS", "OUT-ERR-002")
    TOPIC_NOT_INACTIVE = ("TOPIC_NOT_INACTIVE", "OUT-ERR-003")

    # Template Errors
    TEMPLATE_NOT_FOUND = ("TEMPLATE_NOT_FOUND", "TPL-ERR-001")
    TEMPLATE_ALREADY_EXISTS = ("TEMPLATE_ALREADY_EXISTS", "TPL-ERR-002")

    # Subscription Errors
    SUBSCRIPTION_CALL_FAILED = ("SUBSCRIPTION_CALL_FAILED", "SUB-ERR-001")

    # Registry Configuration Errors
    REGISTRY_CONFIGURATION_NOT_FOUND = ("REGISTRY_CONFIGURATION_NOT_FOUND", "RCF-ERR-001")
    REGISTRY_CONFIGURATION_EXISTS = ("REGISTRY_CONFIGURATION_EXISTS", "RCF-ERR-002")

    # VC Config Errors
    VC_CONFIGURATION_NOT_FOUND = ("VC_CONFIGURATION_NOT_FOUND", "VCF-ERR-001")
