import enum


class G2PRegistryErrorCodes(enum.Enum):
    # Request Validation Errors
    REQUEST_VALIDATION_ERROR = ("REQUEST_VALIDATION_ERROR", "REQ-VAL-001")

    # Database Errors
    DATABASE_CONNECTION_ERROR = ("DATABASE_CONNECTION_ERROR", "DB-ERR-001")
    DATABASE_QUERY_ERROR = ("DATABASE_QUERY_ERROR", "DB-ERR-002")
    DATABASE_TRANSACTION_ERROR = ("DATABASE_TRANSACTION_ERROR", "DB-ERR-003")

    # Register Errors
    REGISTER_NOT_FOUND = ("REGISTER_NOT_FOUND", "REG-ERR-001")
    REGISTER_DATA_NOT_FOUND = ("REGISTER_DATA_NOT_FOUND", "REG-ERR-002")

