import enum


class G2PRegistryErrorCodes(enum.Enum):
    # Request Validation Errors
    INVALID_REQUEST = ("INVALID_REQUEST", "REQ-VAL-000")
    REQUEST_VALIDATION_ERROR = ("REQUEST_VALIDATION_ERROR", "REQ-VAL-001")

    # Database Errors
    DATABASE_CONNECTION_ERROR = ("DATABASE_CONNECTION_ERROR", "DB-ERR-001")
    DATABASE_QUERY_ERROR = ("DATABASE_QUERY_ERROR", "DB-ERR-002")
    DATABASE_TRANSACTION_ERROR = ("DATABASE_TRANSACTION_ERROR", "DB-ERR-003")

    # Register Errors
    REGISTER_NOT_FOUND = ("REGISTER_NOT_FOUND", "REG-ERR-001")
    REGISTER_DATA_NOT_FOUND = ("REGISTER_DATA_NOT_FOUND", "REG-ERR-002")
    CHANGE_LOG_NOT_FOUND = ("CHANGE_LOG_NOT_FOUND", "REG-ERR-003")
    CHANGE_LOG_NOT_IN_PENDING_STATE = ("CHANGE_LOG_NOT_IN_PENDING_STATE", "REG-ERR-004")
    VERIFICATIONS_PENDING = ("VERIFICATIONS_PENDING", "REG-ERR-005")
    OPERATION_NOT_FOUND = ("OPERATION_NOT_FOUND", "REG-ERR-006")

    # Partner Errors
    PARTNER_NOT_REGISTERED = ("PARTNER_NOT_REGISTERED", "REGP-ERR-001")
    DATA_MODEL_NOT_FOUND = ("DATA_MODEL_NOT_FOUND", "REGP-ERR-002")

    # Subscription Errors
    SUBSCRIPTION_CALL_FAILED = ("SUBSCRIPTION_CALL_FAILED", "SUB-ERR-001")


